### ISSUE TITLE
(reviewed) Tests for CreateForm

### ISSUE THREAD

**Issue by lkk95** [lkk95/capstone-project#14]
## User Story
- As a developer  
- I want to write tests for my CreateForm component 
- so that i can see if the input fields and submit in the form behave correctly 

## AC
- text input test 
- radio button test

## Tasks
- [ ] create new branch
- [ ] create test file for CreateForm component
- [ ] write test for checking if text input has correct value when typing something
- [ ] write test for checking if radio button is checked when clicked and if other buttons are not checked
- [ ] run tests to see if they pass

## Complexity
high

## Linked to issue
#4

**Comment by p-enz** [comment]
Hey Laura, your Story looks good to me. Maybe you could slice it a bit smaller. Maybe test the inputs and radio buttons in separate stories. Helps maybe for small success

**Comment by lkk95** [comment]
Hey Philipp, thanks for your review and suggestion! I already have the input test almost complete, so it will only be the radio button test that I have to put time into. But for future testing stories I will keep this in mind. :)
