### ISSUE TITLE
Image Upload for Edit Form

### ISSUE THREAD

**Issue by lkk95** [lkk95/capstone-project#30]
## User Story
- As a user
- I want an image upload in edit form
- so that I can change my picture for the recipe

## AC
- input for uploading files
- image is saved in correct format in data set

## Design/Wireframe
![image](https://user-images.githubusercontent.com/90553245/177355699-c14d3a35-3873-4b5a-b9e2-f560a36ad91c.png)

## Tasks
- [ ] create new branch
- [ ] add input for files to edit form
- [ ] restrict file upload to only image formats
- [ ] save file in zustand

## Complexity
medium

## Linked to issue
#10
