### ISSUE TITLE
Edit Form as Modal

### ISSUE THREAD

**Issue by lkk95** [lkk95/capstone-project#31]
## User Story
- As a user 
- I want to have the editing form opened as a modal 
- so that it looks nicer when I edit meals

## AC
- modal component with functionality in Detailspage
- edit form as child of modal component

## Tasks
- [ ] create new branch
- [ ] implement Modal component in Detailspage
- [ ] add EditForm component as child to Modal 
- [ ] add state for toggling Modal to form buttons and edit button

## Complexity
medium

## Linked to issue
#10
