### ISSUE TITLE
(reviewed) Shopping List Page

### ISSUE THREAD

**Issue by lkk95** [lkk95/capstone-project#39]
## User Story
- As a user
- I want to have a shoppinglist
- so that I know what to buy for my planned meals

## AC
- new page Shopping List
- ingredients of recipes are displayed as list with checkboxes

## Design/Wireframe
![image](https://user-images.githubusercontent.com/90553245/178289300-cf8c0e29-b480-4ce8-99c5-96da5b91954c.png)

## Tasks
- [x] create new branch 
- [x] create new page Shopping List
- [x] add icon to Navbar
- [x] add routing to Navbar icon
- [x] get ingredients arrays from meals list 
- [x] render all ingredients with checkboxes

## Complexity 
medium
