### ISSUE TITLE
Design Shopping List

### ISSUE THREAD

**Issue by lkk95** [lkk95/capstone-project#40]
## Developer Story
- As a developer
- I want a nice and responsive design for the shopping list
- so that the website looks good on all devices 

## AC 
- final fonts, colors and icons are implemented
- responsive design is implemented

## Tasks
- [x] create new branch
- [x] apply fonts, colors and icons
- [x] apply responsive design

## Complexity
low
